import type { AdventureStage } from '@/types/adventure';

export const adventureStages: AdventureStage[] = [
  // Chapter 1: The Arrival
  {
    id: 'stage-01-mist-gate',
    chapterId: 'chapter-arrival',
    order: 1,
    title: 'The Mist Gate',
    narrative:
      'At the resort entrance, a carved wooden sign reads: "Where clouds descend, stories ascend." The morning mist curls around the mountain pines. Your welcome card bears a single clue — find the word the valley whispers at dawn.',
    clueType: 'keyword',
    locationType: 'resort',
    locationName: 'Resort Main Entrance',
    unlockRequirement: {},
    hints: [
      { level: 1, text: 'Look at what drapes the peaks each morning.', cooldownMinutes: 2 },
      { level: 2, text: 'The answer is a four-letter word for morning fog.', cooldownMinutes: 5 },
    ],
    puzzle: {
      id: 'puzzle-01',
      type: 'keyword',
      prompt: 'What word does the valley whisper at dawn? (Check the carved sign for inspiration)',
      config: { type: 'keyword', answers: ['mist', 'fog'], caseSensitive: false },
    },
    artifact: {
      id: 'artifact-mist-token',
      name: 'Mist Token',
      description: 'A small wooden token carved with swirling mist patterns.',
      flavorText: 'The first keeper left this for those who arrive with open eyes.',
    },
    storyFragment:
      'The legend speaks of a lantern lit only when four keepers reunite their tokens. You have found the first.',
    safetyNote: 'Stay on paved resort paths. No off-trail exploration required.',
    estimatedDurationMinutes: 15,
    accessibilityNotes: 'Fully accessible from main entrance. Staff assistance available.',
    isFictionalStory: true,
    daylightOnly: false,
    mapZone: { x: 50, y: 50 },
  },
  {
    id: 'stage-02-old-map',
    chapterId: 'chapter-arrival',
    order: 2,
    title: 'The Old Map',
    narrative:
      'In the reception hall, an antique map of the valley hangs beside the guest book. Three symbols mark story stations — a pine, a star, and a lantern. One symbol points to where guests gather stories over tea.',
    clueType: 'observation',
    locationType: 'resort',
    locationName: 'Reception Hall',
    unlockRequirement: { previousStageId: 'stage-01-mist-gate' },
    hints: [
      {
        level: 1,
        text: 'The map uses symbols, not words. Which marks a social gathering place?',
        cooldownMinutes: 3,
      },
      { level: 2, text: 'Tea is central to hill-country hospitality.', cooldownMinutes: 5 },
    ],
    puzzle: {
      id: 'puzzle-02',
      type: 'multiple_choice',
      prompt: 'Which symbol on the old map marks where guests gather for tea and stories?',
      config: {
        type: 'multiple_choice',
        options: [
          'The pine tree symbol',
          'The star symbol',
          'The teacup symbol',
          'The lantern symbol',
        ],
        correctIndex: 2,
      },
    },
    artifact: {
      id: 'artifact-map-corner',
      name: 'Torn Map Corner',
      description: 'A fragment of the antique map showing a garden path.',
      flavorText: 'The garden path on this fragment matches the whispering herbs ahead.',
    },
    storyFragment:
      'The second keeper hid map fragments so only the observant would find the garden trail.',
    safetyNote:
      'Reception area only. Do not handle fragile map — observation from a respectful distance.',
    estimatedDurationMinutes: 10,
    accessibilityNotes: 'Reception is fully accessible.',
    isFictionalStory: true,
    daylightOnly: false,
    mapZone: { x: 48, y: 52 },
  },
  {
    id: 'stage-03-reception-riddle',
    chapterId: 'chapter-arrival',
    order: 3,
    title: 'The Reception Riddle',
    narrative:
      'The guest book contains a riddle in elegant script: "I have roots but no soil, branches but no leaves. Hill-country families gather beneath me for stories. What am I?"',
    clueType: 'riddle',
    locationType: 'resort',
    locationName: 'Reception Desk',
    unlockRequirement: { previousStageId: 'stage-02-old-map' },
    hints: [
      {
        level: 1,
        text: 'Think of where families gather outdoors at the resort.',
        cooldownMinutes: 3,
      },
      { level: 2, text: 'Campfire evenings take place around one of these.', cooldownMinutes: 5 },
    ],
    puzzle: {
      id: 'puzzle-03',
      type: 'riddle',
      prompt: 'Solve the riddle from the guest book.',
      config: { type: 'riddle', answers: ['fire', 'campfire', 'bonfire', 'flame'] },
    },
    artifact: {
      id: 'artifact-ember-stone',
      name: 'Ember Stone',
      description: 'A smooth stone warm to the touch, marked with a tiny flame etching.',
      flavorText: 'Chapter One complete. The garden whispers await.',
    },
    storyFragment: 'Three artifacts of The Arrival. The Whispering Garden opens its gates to you.',
    safetyNote: 'Interact with reception staff if you need the riddle read aloud.',
    estimatedDurationMinutes: 15,
    accessibilityNotes: 'Staff can read the riddle and provide assistance.',
    isFictionalStory: true,
    daylightOnly: false,
    mapZone: { x: 50, y: 54 },
  },

  // Chapter 2: The Whispering Garden
  {
    id: 'stage-04-garden-path',
    chapterId: 'chapter-garden',
    order: 4,
    title: 'Garden Path Sequence',
    narrative:
      'The herb garden has four marked stations: Lemongrass, Cinnamon, Cardamom, and Clove. The torn map fragment shows the correct walking order for the story ritual.',
    clueType: 'sequence',
    locationType: 'resort',
    locationName: 'Herb Garden',
    unlockRequirement: { previousStageId: 'stage-03-reception-riddle' },
    hints: [
      {
        level: 1,
        text: 'Cinnamon comes before cardamom in the traditional spice blessing.',
        cooldownMinutes: 3,
      },
      { level: 2, text: 'Order: Lemongrass → Cinnamon → Cardamom → Clove', cooldownMinutes: 8 },
    ],
    puzzle: {
      id: 'puzzle-04',
      type: 'sequence',
      prompt: 'Order the herbs in the correct ritual sequence (drag or select order 1-4).',
      config: {
        type: 'sequence',
        items: ['Lemongrass', 'Cinnamon', 'Cardamom', 'Clove'],
        correctOrder: [0, 1, 2, 3],
      },
    },
    artifact: {
      id: 'artifact-herb-bundle',
      name: 'Pressed Herb Bundle',
      description: 'Dried herbs tied with natural fiber, scented with hill-country spices.',
      flavorText: 'The garden keeper pressed these for travelers who walk with patience.',
    },
    storyFragment:
      'The herbs remember every story told beside them. You are now part of that memory.',
    safetyNote: 'Stay on marked garden paths. Do not pick living plants.',
    estimatedDurationMinutes: 20,
    accessibilityNotes: 'Garden paths are mostly level. Guided option available.',
    isFictionalStory: true,
    daylightOnly: true,
    mapZone: { x: 42, y: 58 },
  },
  {
    id: 'stage-05-hidden-bench',
    chapterId: 'chapter-garden',
    order: 5,
    title: 'The Hidden Bench',
    narrative:
      'Beneath the oldest jackfruit tree, a bench bears a carved inscription worn by rain. The first word is hidden — only the second word "lantern" is visible. The missing word describes what falls from jackfruit trees in the monsoon.',
    clueType: 'keyword',
    locationType: 'resort',
    locationName: 'Jackfruit Tree Bench',
    unlockRequirement: { previousStageId: 'stage-04-garden-path' },
    hints: [
      { level: 1, text: 'Monsoon season brings heavy ___ from fruit trees.', cooldownMinutes: 3 },
      {
        level: 2,
        text: 'The answer is "rain". Enter: rain lantern as keyword "rain".',
        cooldownMinutes: 6,
      },
    ],
    puzzle: {
      id: 'puzzle-05',
      type: 'keyword',
      prompt: 'What word completes the bench inscription before "lantern"?',
      config: { type: 'keyword', answers: ['rain', 'rains'] },
    },
    artifact: {
      id: 'artifact-bench-nail',
      name: 'Carved Bench Nail',
      description: 'A decorative nail from the garden bench, shaped like a raindrop.',
      flavorText: 'Rain and lantern — two words that guide stargazers.',
    },
    storyFragment:
      'The bench points skyward. The star chart near the observatory deck holds the next clue.',
    safetyNote: 'Bench area is on resort grounds. Daylight recommended for garden navigation.',
    estimatedDurationMinutes: 15,
    accessibilityNotes: 'Bench accessible via garden path. Staff escort available.',
    isFictionalStory: true,
    daylightOnly: true,
    mapZone: { x: 40, y: 60 },
  },
  {
    id: 'stage-06-star-chart',
    chapterId: 'chapter-garden',
    order: 6,
    title: 'The Star Chart',
    narrative:
      'On the observatory deck, a brass star chart shows constellations visible from Nugawela. The storytellers marked the "Navigator\'s Cross" with a distinctive symbol — a four-pointed star with a circle at its center.',
    clueType: 'symbol',
    locationType: 'resort',
    locationName: 'Observatory Deck',
    unlockRequirement: { previousStageId: 'stage-05-hidden-bench' },
    hints: [
      {
        level: 1,
        text: 'Look for the symbol described: four points with a center circle.',
        cooldownMinutes: 3,
      },
      { level: 2, text: 'Select the ✦ symbol (four-pointed star with dot).', cooldownMinutes: 5 },
    ],
    puzzle: {
      id: 'puzzle-06',
      type: 'symbol',
      prompt: "Which symbol marks the Navigator's Cross on the chart?",
      config: {
        type: 'symbol',
        symbols: ['★', '✦', '☆', '✧', '⊕'],
        correctSymbol: '✦',
      },
    },
    artifact: {
      id: 'artifact-star-disc',
      name: 'Brass Star Disc',
      description: "A small brass disc engraved with the Navigator's Cross.",
      flavorText: 'Chapter Two complete. The valley keepers await your arrival.',
    },
    storyFragment: 'The cross points toward the village. Story-keepers hold the next fragments.',
    safetyNote: 'Observatory deck has railings. Supervised stargazing only after dark.',
    estimatedDurationMinutes: 20,
    accessibilityNotes: 'Deck accessible with ramp. Night visits require staff guide.',
    isFictionalStory: true,
    daylightOnly: true,
    mapZone: { x: 38, y: 55 },
  },

  // Chapter 3: The Keepers of the Valley
  {
    id: 'stage-07-tea-keeper',
    chapterId: 'chapter-keepers',
    order: 7,
    title: 'The Tea Shop Keeper',
    narrative:
      'At the approved partner tea shop (marked on your map), the story keeper will share a clue only after you speak the unlock phrase from your Mist Token. The phrase is carved on its back: "VALLEY-MIST-01".',
    clueType: 'staff_checkpoint',
    locationType: 'partner',
    locationName: 'Partner Tea Shop (Approved Station)',
    unlockRequirement: { previousStageId: 'stage-06-star-chart' },
    hints: [
      {
        level: 1,
        text: 'Visit the tea shop during opening hours with your Mist Token.',
        cooldownMinutes: 5,
      },
      { level: 2, text: 'Enter the checkpoint code: VALLEY-MIST-01', cooldownMinutes: 10 },
    ],
    puzzle: {
      id: 'puzzle-07',
      type: 'staff_checkpoint',
      prompt: 'Enter the unlock phrase from your Mist Token, or the staff checkpoint code.',
      config: {
        type: 'staff_checkpoint',
        checkpointCode: 'VALLEY-MIST-01',
        staffPhrase: 'valley-mist-01',
      },
    },
    artifact: {
      id: 'artifact-tea-leaf',
      name: 'Golden Tea Leaf',
      description: 'A preserved tea leaf pressed in wax, gift of the tea shop keeper.',
      flavorText: 'Real Ceylon tea connects every hill-country story.',
    },
    storyFragment:
      'The tea keeper speaks of an artisan who carves stories into wood. Visit only during approved hours.',
    safetyNote: 'Partner location only. Do not enter private homes. Daylight hours only.',
    estimatedDurationMinutes: 30,
    accessibilityNotes: 'Tea shop has step-free entry. Staff keeper provides verbal clues.',
    isFictionalStory: false,
    daylightOnly: true,
    mapZone: { x: 35, y: 45 },
  },
  {
    id: 'stage-08-artisan-cipher',
    chapterId: 'chapter-keepers',
    order: 8,
    title: "The Artisan's Cipher",
    narrative:
      'The artisan workshop displays a carved panel with encoded text: "WKHT WR QHTKH" — a simple Caesar cipher shifting each letter back by one. Decipher to find the tool used to carve these panels.',
    clueType: 'cipher',
    locationType: 'partner',
    locationName: 'Artisan Workshop (Approved Station)',
    unlockRequirement: { previousStageId: 'stage-07-tea-keeper' },
    hints: [
      {
        level: 1,
        text: 'Shift each letter one position earlier in the alphabet.',
        cooldownMinutes: 4,
      },
      {
        level: 2,
        text: 'WKHT → VISE, WR → VQ, QHTKH → PGSKG. Answer: chisel or knife.',
        cooldownMinutes: 8,
      },
    ],
    puzzle: {
      id: 'puzzle-08',
      type: 'cipher',
      prompt: 'Decipher the panel text (Caesar cipher, shift -1). What carving tool does it name?',
      config: {
        type: 'cipher',
        encoded: 'WKHT WR QHTKH',
        answers: ['chisel', 'knife', 'blade'],
        hint: 'Shift each letter one back in the alphabet',
      },
    },
    artifact: {
      id: 'artifact-wood-chip',
      name: 'Carved Wood Chip',
      description: 'A delicate wood carving showing a lantern outline.',
      flavorText: 'The artisan whispers: the temple courtyard holds a truth older than the story.',
    },
    storyFragment: 'Wood and stone remember what paper forgets. The heritage temple route awaits.',
    safetyNote: 'Workshop is a registered partner station. Photography with permission only.',
    estimatedDurationMinutes: 25,
    accessibilityNotes: 'Workshop entrance has one step. Staff can bring clues outside.',
    isFictionalStory: false,
    daylightOnly: true,
    mapZone: { x: 50, y: 70 },
  },
  {
    id: 'stage-09-temple-courtyard',
    chapterId: 'chapter-keepers',
    order: 9,
    title: 'Temple Courtyard Question',
    narrative:
      'At the heritage temple (approved visit route), a guide asks a cultural question before revealing the ridge clue. This is real hill-country heritage — separate from the fictional lantern tale.',
    clueType: 'multiple_choice',
    locationType: 'partner',
    locationName: 'Heritage Temple Route (Approved)',
    unlockRequirement: { previousStageId: 'stage-08-artisan-cipher' },
    hints: [
      {
        level: 1,
        text: 'Tea cultivation transformed the central highlands in the 19th century.',
        cooldownMinutes: 4,
      },
      { level: 2, text: 'The answer relates to tea plantations.', cooldownMinutes: 6 },
    ],
    puzzle: {
      id: 'puzzle-09',
      type: 'multiple_choice',
      prompt: 'What crop transformed the Sri Lankan hill country in the 19th century?',
      config: {
        type: 'multiple_choice',
        options: ['Rubber', 'Tea', 'Coffee', 'Coconut'],
        correctIndex: 1,
        isFictionalNote: true,
      },
    },
    artifact: {
      id: 'artifact-temple-thread',
      name: 'Blessed Thread',
      description: 'A simple thread bracelet given at the temple courtyard (optional tradition).',
      flavorText: 'Chapter Three complete. The ridge lantern is near.',
    },
    storyFragment:
      'The final keeper watches the ridge at dusk. Bring all artifacts. Bring respect.',
    safetyNote: 'Dress modestly. Remove shoes in sacred areas. Follow guide instructions.',
    estimatedDurationMinutes: 40,
    accessibilityNotes: 'Some steps at temple entrance. Alternative access with guide.',
    isFictionalStory: false,
    daylightOnly: true,
    mapZone: { x: 55, y: 68 },
  },

  // Chapter 4: The Final Lantern
  {
    id: 'stage-10-ridge-pin',
    chapterId: 'chapter-lantern',
    order: 10,
    title: 'Ridge Viewpoint Selection',
    narrative:
      'The adventure guide shows a simplified ridge map with three viewpoints. Only one is approved for the lantern ceremony — the supervised eastern ridge with staff presence and safety railings.',
    clueType: 'map_pin',
    locationType: 'approved_outdoor',
    locationName: 'Ridge Trail Junction',
    unlockRequirement: { previousStageId: 'stage-09-temple-courtyard' },
    hints: [
      {
        level: 1,
        text: 'Choose the viewpoint marked as supervised with safety railings.',
        cooldownMinutes: 3,
      },
      { level: 2, text: 'Eastern Supervised Ridge is the approved location.', cooldownMinutes: 5 },
    ],
    puzzle: {
      id: 'puzzle-10',
      type: 'map_pin',
      prompt: 'Which viewpoint is approved for the lantern ceremony?',
      config: {
        type: 'map_pin',
        options: [
          { id: 'west-cliff', label: 'West Cliff (unmarked trail)' },
          { id: 'east-ridge', label: 'Eastern Supervised Ridge' },
          { id: 'north-forest', label: 'North Forest (closed)' },
        ],
        correctId: 'east-ridge',
      },
    },
    artifact: {
      id: 'artifact-ridge-pebble',
      name: 'Ridge Pebble',
      description: 'A smooth pebble from the supervised ridge path.',
      flavorText: 'The lantern keeper waits at the eastern ridge before sunset.',
    },
    storyFragment: 'One riddle remains. Then the lantern may be lit.',
    safetyNote: 'Never visit ridge viewpoints alone. Guided groups only. Return before dusk.',
    estimatedDurationMinutes: 45,
    accessibilityNotes:
      'Ridge trail is moderate difficulty. Staff-assisted option for limited mobility.',
    isFictionalStory: true,
    daylightOnly: true,
    mapZone: { x: 60, y: 30 },
  },
  {
    id: 'stage-11-keeper-riddle',
    chapterId: 'chapter-lantern',
    order: 11,
    title: "The Story Keeper's Riddle",
    narrative:
      'At the eastern ridge station, the story keeper speaks: "I light the darkness but fear the wind. I dance without legs and warm without fire. What am I?"',
    clueType: 'riddle',
    locationType: 'approved_outdoor',
    locationName: 'Eastern Supervised Ridge',
    unlockRequirement: { previousStageId: 'stage-10-ridge-pin' },
    hints: [
      { level: 1, text: 'The final chapter title holds the answer.', cooldownMinutes: 4 },
      { level: 2, text: 'What lights the darkness on a ridge at dusk?', cooldownMinutes: 7 },
    ],
    puzzle: {
      id: 'puzzle-11',
      type: 'riddle',
      prompt: "Solve the story keeper's riddle.",
      config: { type: 'riddle', answers: ['lantern', 'light', 'lamp'] },
    },
    artifact: {
      id: 'artifact-wick-wrap',
      name: 'Wick Wrap',
      description: 'A cloth wrap used to protect lantern wicks in hill-country wind.',
      flavorText: 'One final word unlocks the lantern. Speak it with intention.',
    },
    storyFragment: 'All keepers have contributed. The lantern awaits your final word.',
    safetyNote: 'Stay within marked ridge area. Guide must be present.',
    estimatedDurationMinutes: 30,
    accessibilityNotes: 'Guide reads riddle aloud. Rest area available at ridge station.',
    isFictionalStory: true,
    daylightOnly: true,
    mapZone: { x: 62, y: 28 },
  },
  {
    id: 'stage-12-final-lantern',
    chapterId: 'chapter-lantern',
    order: 12,
    title: 'The Final Lantern',
    narrative:
      'Twelve artifacts gathered. The lantern stands ready. Enter the final phrase spoken by every keeper when the mist clears: "NUGAWELA LIGHTS THE WAY".',
    clueType: 'keyword',
    locationType: 'approved_outdoor',
    locationName: 'Lantern Ceremony Point',
    unlockRequirement: { previousStageId: 'stage-11-keeper-riddle' },
    hints: [
      { level: 1, text: 'The phrase begins with NUGAWELA.', cooldownMinutes: 5 },
      { level: 2, text: 'Full phrase: NUGAWELA LIGHTS THE WAY', cooldownMinutes: 10 },
    ],
    puzzle: {
      id: 'puzzle-12',
      type: 'keyword',
      prompt: 'Speak the final keeper phrase to light the lantern.',
      config: {
        type: 'keyword',
        answers: ['nugawela lights the way', 'nugawela'],
        caseSensitive: false,
      },
    },
    artifact: {
      id: 'artifact-final-lantern',
      name: 'Miniature Lantern',
      description: 'A gift replica of the ridge lantern — your completion trophy.',
      flavorText: 'You have walked The Hidden Trail of Nugawela. The valley remembers you.',
    },
    storyFragment:
      'The four chapters unite. The mist lifts. Your story becomes part of Nugawela forever.',
    safetyNote:
      'Ceremony supervised by staff. Celebration at ridge station — no unsupervised descent after dark.',
    estimatedDurationMinutes: 20,
    accessibilityNotes: 'Ceremony area has seating. All guests welcome.',
    isFictionalStory: true,
    daylightOnly: true,
    mapZone: { x: 65, y: 26 },
  },
];
