import { images } from '@/config/images';
import type { Experience } from '@/types';

export const mockExperiences: Experience[] = [
  {
    id: 'exp-nature-walk',
    name: 'Guided Nature Walk',
    slug: 'guided-nature-walk',
    description:
      'Join our resident naturalist through forest trails, identifying endemic birds, medicinal plants, and the subtle signs of hill-country wildlife. Routes adapted to your pace and interests.',
    shortDescription: 'Forest trails with a resident naturalist guide.',
    durationMinutes: 120,
    price: 45,
    currency: 'USD',
    category: 'nature',
    maxParticipants: 8,
    images: [images.experiences.natureWalk],
    featured: true,
  },
  {
    id: 'exp-tea-tasting',
    name: 'Tea & Local Food Experience',
    slug: 'tea-local-food',
    description:
      'Visit a nearby tea estate, learn the art of Ceylon tea production, and return for a curated tasting of hill-country cuisine — from hoppers to wood-fired curries.',
    shortDescription: 'Tea estate visit with curated local food tasting.',
    durationMinutes: 180,
    price: 65,
    currency: 'USD',
    category: 'culinary',
    maxParticipants: 10,
    images: [images.experiences.teaTasting],
    featured: true,
  },
  {
    id: 'exp-campfire',
    name: 'Campfire Evening',
    slug: 'campfire-evening',
    description:
      'Gather around a hillside campfire as local storytellers share legends of the valley. Includes spiced snacks, herbal drinks, and optional stargazing afterward.',
    shortDescription: 'Hillside campfire with local storytelling.',
    durationMinutes: 150,
    price: 35,
    currency: 'USD',
    category: 'cultural',
    maxParticipants: 20,
    images: [images.experiences.campfire],
    featured: true,
  },
  {
    id: 'exp-stargazing',
    name: 'Stargazing Session',
    slug: 'stargazing-session',
    description:
      'With minimal light pollution, Nugawela offers remarkable night skies. Our guide helps you identify constellations, planets, and the stories ancient navigators attached to them.',
    shortDescription: 'Guided stargazing with constellation storytelling.',
    durationMinutes: 90,
    price: 40,
    currency: 'USD',
    category: 'adventure',
    maxParticipants: 12,
    images: [images.experiences.stargazing],
    featured: false,
  },
  {
    id: 'exp-village-walk',
    name: 'Village Story Walk',
    slug: 'village-story-walk',
    description:
      'Walk through Nugawela village with a local guide, visiting artisan workshops, heritage homes, and community spaces. Learn how hill-country life has evolved across generations.',
    shortDescription: 'Guided village walk with artisan and heritage stops.',
    durationMinutes: 150,
    price: 50,
    currency: 'USD',
    category: 'cultural',
    maxParticipants: 8,
    images: [images.destinations.village],
    featured: false,
  },
  {
    id: 'exp-photography',
    name: 'Photography Trail',
    slug: 'photography-trail',
    description:
      'Capture the golden light of the highlands with a photography guide who knows every viewpoint, hidden waterfall, and misty ridge. Equipment tips included.',
    shortDescription: 'Photography guide to the best hill-country viewpoints.',
    durationMinutes: 180,
    price: 75,
    currency: 'USD',
    category: 'adventure',
    maxParticipants: 6,
    images: [images.experiences.natureWalk],
    featured: false,
  },
];
