import { images } from '@/config/images';
import type { Room } from '@/types';

export const mockRooms: Room[] = [
  {
    id: 'room-mountain-suite',
    name: 'Mountain View Suite',
    slug: 'mountain-view-suite',
    type: 'suite',
    description:
      'Wake to panoramic views of the mist-draped peaks of the central highlands. This spacious suite features a private terrace, handcrafted teak furnishings, and a soaking tub overlooking the valley. Perfect for couples seeking calm luxury above the clouds.',
    shortDescription: 'Panoramic mountain views with private terrace and soaking tub.',
    maxGuests: 2,
    basePricePerNight: 285,
    currency: 'USD',
    viewType: 'mountain',
    amenities: [
      'Private terrace',
      'Soaking tub',
      'Mountain view',
      'Mini bar',
      'Rain shower',
      'Tea & coffee station',
      'Wi-Fi',
      'Air conditioning',
    ],
    images: [images.rooms.mountainSuite],
    featured: true,
    sizeSqm: 52,
  },
  {
    id: 'room-forest-chalet',
    name: 'Forest Hideaway Chalet',
    slug: 'forest-hideaway-chalet',
    type: 'chalet',
    description:
      'Nestled at the edge of the resort forest, this secluded chalet offers an immersive nature experience. Floor-to-ceiling windows frame ancient trees, while the outdoor deck invites morning birdwatching and evening stargazing.',
    shortDescription: 'Secluded forest retreat with floor-to-ceiling windows.',
    maxGuests: 2,
    basePricePerNight: 220,
    currency: 'USD',
    viewType: 'forest',
    amenities: [
      'Forest view',
      'Outdoor deck',
      'Fireplace',
      'Reading nook',
      'Wi-Fi',
      'Tea & coffee station',
      'Rain shower',
    ],
    images: [images.rooms.forestChalet],
    featured: true,
    sizeSqm: 38,
  },
  {
    id: 'room-heritage-villa',
    name: 'Heritage Family Villa',
    slug: 'heritage-family-villa',
    type: 'villa',
    description:
      'A two-bedroom villa blending colonial hill-country architecture with modern comfort. Ideal for families, with a shared living space, garden courtyard access, and stories of the valley woven into its design.',
    shortDescription: 'Two-bedroom villa with colonial charm and garden access.',
    maxGuests: 5,
    basePricePerNight: 380,
    currency: 'USD',
    viewType: 'garden',
    amenities: [
      'Two bedrooms',
      'Living area',
      'Garden access',
      'Kitchenette',
      'Family bathroom',
      'Wi-Fi',
      'Air conditioning',
      'Daily housekeeping',
    ],
    images: [images.rooms.heritageVilla],
    featured: true,
    sizeSqm: 85,
  },
  {
    id: 'room-stargazer-cabin',
    name: 'Stargazer Cabin',
    slug: 'stargazer-cabin',
    type: 'cabin',
    description:
      'A compact cabin designed for night-sky enthusiasts. The skylight above the bed reveals constellations unobstructed by city lights. Includes a star chart, binoculars, and a guide to local celestial landmarks.',
    shortDescription: 'Skylight cabin for stargazing with included star chart.',
    maxGuests: 2,
    basePricePerNight: 195,
    currency: 'USD',
    viewType: 'valley',
    amenities: [
      'Skylight',
      'Star chart',
      'Binoculars',
      'Valley view',
      'Compact kitchenette',
      'Wi-Fi',
      'Heated floors',
    ],
    images: [images.rooms.stargazerCabin],
    featured: false,
    sizeSqm: 28,
  },
  {
    id: 'room-garden-courtyard',
    name: 'Garden Courtyard Room',
    slug: 'garden-courtyard-room',
    type: 'room',
    description:
      "Opening directly onto the resort's herb and flower courtyard, this ground-floor room offers easy access to garden paths and the morning mist. A peaceful choice for guests who love to wander.",
    shortDescription: 'Ground-floor room with direct courtyard and garden access.',
    maxGuests: 2,
    basePricePerNight: 165,
    currency: 'USD',
    viewType: 'courtyard',
    amenities: [
      'Courtyard access',
      'Garden view',
      'Ground floor',
      'Rain shower',
      'Wi-Fi',
      'Tea & coffee station',
      'Writing desk',
    ],
    images: [images.rooms.gardenRoom],
    featured: false,
    sizeSqm: 32,
  },
];
