import type { TravelUpdate } from '@/types/travel';

export const mockUpdates: TravelUpdate[] = [
  {
    id: 'upd-east-season',
    title: 'East Coast Season Opens for Surf & Swims',
    slug: 'east-coast-season-opens',
    summary: 'May–September conditions favor Arugam Bay, Passikudah, and Nilaveli.',
    body: 'As the southwest monsoon settles on the west and south, the east coast typically enjoys calmer seas and reliable surf. Operators in Arugam Bay and snorkel boats from Nilaveli enter peak visitor weeks — reserve popular activities ahead of weekends.',
    category: 'seasonal',
    publishedAt: '2026-05-02',
    featured: true,
    relatedSlugs: ['arugam-bay-surfing', 'pigeon-island-snorkelling'],
  },
  {
    id: 'upd-minneriya',
    title: 'Minneriya Elephant Gathering Watch',
    slug: 'minneriya-gathering-watch',
    summary: 'Dry-season tank levels draw large elephant herds — go early and keep distance.',
    body: 'Park trackers report increasing herd concentrations around Minneriya tank. Visitors should choose licensed jeeps, avoid blocking animal corridors, and prioritize morning drives for softer light and cooler temperatures.',
    category: 'park',
    publishedAt: '2026-07-18',
    featured: true,
    relatedSlugs: ['wildlife-circuit', 'yala-wildlife-safari'],
  },
  {
    id: 'upd-ella-trail',
    title: 'Ella Rock Path Maintenance Notice',
    slug: 'ella-rock-maintenance',
    summary: 'Sections after rain can be slick; local guides recommend later morning starts this week.',
    body: 'Recent showers have left clay stretches near the mid-trail tea fields muddy. Hikers should wear grippy footwear and consider postponing summit attempts during active rain. Little Adam’s Peak remains a clearer alternative.',
    category: 'trail',
    publishedAt: '2026-06-11',
    featured: false,
    relatedSlugs: ['ella-rock-trail', 'little-adams-peak'],
  },
  {
    id: 'upd-kandy-esala',
    title: 'Kandy Esala Perahera Season Preview',
    slug: 'kandy-esala-preview',
    summary: 'Festival nights fill the lake city — plan lodging and temple visits early.',
    body: 'The Esala season brings processions, dancers, and packed lakeside streets. Daytime temple visits remain possible with patience; evening viewing spots fill quickly. Dress modestly and secure belongings in crowds.',
    category: 'festival',
    publishedAt: '2026-07-01',
    featured: true,
    relatedSlugs: ['kandy-cultural-immersion', 'hill-country'],
  },
  {
    id: 'upd-whale',
    title: 'Mirissa Whale Season Outlook',
    slug: 'mirissa-whale-outlook',
    summary: 'Boats are running; sightings vary with swell and migratory patterns.',
    body: 'Operators report active mornings when seas allow. Choose tours that follow responsible wildlife guidelines and be flexible if departures cancel for safety.',
    category: 'seasonal',
    publishedAt: '2026-01-20',
    featured: false,
    relatedSlugs: ['mirissa-whale-watching'],
  },
  {
    id: 'upd-conservation',
    title: 'Coastal Turtle Nesting Reminder',
    slug: 'turtle-nesting-reminder',
    summary: 'Keep beaches dark and clear on known nesting stretches.',
    body: 'Conservation groups ask travelers to avoid flashlight use on nesting beaches at night, skip collecting shells, and support licensed hatcheries rather than unregulated stalls.',
    category: 'conservation',
    publishedAt: '2026-03-08',
    featured: false,
  },
  {
    id: 'upd-train',
    title: 'Upcountry Train Seat Demand High',
    slug: 'upcountry-train-demand',
    summary: 'Kandy–Ella segments fill quickly on clear-season weekends.',
    body: 'Travelers chasing the scenic railway should reserve seats as early as booking windows allow, or build buffer days for waitlisted coaches. Midweek rides are often calmer.',
    category: 'news',
    publishedAt: '2026-02-14',
    featured: true,
    relatedSlugs: ['scenic-train-journey'],
  },
  {
    id: 'upd-advisory',
    title: 'Midday Heat Advisory for Cultural Triangle',
    slug: 'triangle-heat-advisory',
    summary: 'Climb rocks and ruins early; hydrate often in the dry zone.',
    body: 'Afternoon temperatures at Sigiriya and open archaeological sites can be intense. Schedule summit climbs at dawn and temple visits for early morning or late afternoon.',
    category: 'advisory',
    publishedAt: '2026-06-22',
    featured: false,
    relatedSlugs: ['pidurangala-rock', 'cultural-triangle'],
  },
];
