import { images } from '@/config/images';
import type { TravelTrail } from '@/types/travel';

export const mockTrails: TravelTrail[] = [
  {
    id: 'trail-ella-rock',
    name: 'Ella Rock Trail',
    slug: 'ella-rock-trail',
    shortDescription: 'Signature highland hike through tea and forest to a panoramic summit.',
    overview:
      'A rewarding climb from Ella town through railway tracks, tea estates, and forest to Ella Rock’s open summit views.',
    distanceKm: 8.5,
    durationHours: 4,
    difficulty: 'challenging',
    elevationGainM: 550,
    scenicHighlights: ['Tea terraces', 'Forest canopy', 'Valley panorama'],
    bestSeason: 'January–March',
    safetyAdvice: ['Start by 6–7am', 'Carry water', 'Avoid unmarked side paths after rain'],
    nearbyAttractionHints: ['Nine Arch Bridge', 'Little Adam’s Peak', 'Ravana Falls'],
    regionId: 'region-hill-country',
    images: [images.adventure.trail, images.hero.main],
    featured: true,
  },
  {
    id: 'trail-little-adams',
    name: 'Little Adam’s Peak',
    slug: 'little-adams-peak',
    shortDescription: 'Short scenic climb perfect for sunrise or sunset.',
    overview: 'A family-friendly ridge walk with classic Ella valley views and a gentle graded path.',
    distanceKm: 3.2,
    durationHours: 1.5,
    difficulty: 'easy',
    elevationGainM: 180,
    scenicHighlights: ['Sunrise clouds', 'Tea hills', 'Town overlook'],
    bestSeason: 'Year-round',
    safetyAdvice: ['Bring a light layer for wind', 'Stay behind barriers at viewpoints'],
    nearbyAttractionHints: ['Nine Arch Bridge', 'Ella town cafés'],
    regionId: 'region-hill-country',
    images: [images.destinations.sunrise, images.experiences.teaTasting],
    featured: true,
  },
  {
    id: 'trail-horton-plains',
    name: 'Horton Plains Loop',
    slug: 'horton-plains-loop',
    shortDescription: 'Cloud-forest circuit to World’s End and Baker’s Falls.',
    overview:
      'A cool plateau hike through grasslands and forest to the dramatic World’s End cliff and a forest waterfall.',
    distanceKm: 9.5,
    durationHours: 3.5,
    difficulty: 'moderate',
    elevationGainM: 250,
    scenicHighlights: ['World’s End', 'Mini World’s End', 'Baker’s Falls'],
    bestSeason: 'Early mornings January–March for clearer views',
    safetyAdvice: ['Enter park early', 'Fog can obscure cliffs', 'Stay on the loop path'],
    nearbyAttractionHints: ['Nuwara Eliya', 'Ohiya station'],
    regionId: 'region-hill-country',
    images: [images.map.territory, images.adventure.trail],
    featured: true,
  },
  {
    id: 'trail-pidurangala',
    name: 'Pidurangala Rock',
    slug: 'pidurangala-rock',
    shortDescription: 'Sunrise scramble with the classic Sigiriya view.',
    overview:
      'Climb past a temple and boulder sections to a summit ledge facing Sigiriya Rock — best at dawn.',
    distanceKm: 2.5,
    durationHours: 2,
    difficulty: 'moderate',
    elevationGainM: 200,
    scenicHighlights: ['Sigiriya silhouette', 'Dry-zone sunrise', 'Temple cave'],
    bestSeason: 'May–September inland dry season',
    safetyAdvice: ['Torch for pre-dawn', 'Respect temple dress code', 'Careful on summit rocks'],
    nearbyAttractionHints: ['Sigiriya Rock Fortress', 'Village tracks'],
    regionId: 'region-cultural-triangle',
    images: [images.destinations.temple, images.destinations.sunrise],
    featured: true,
  },
  {
    id: 'trail-adams-peak',
    name: 'Adam’s Peak Pilgrim Trail',
    slug: 'adams-peak-trail',
    shortDescription: 'Night climb to a sacred summit for sunrise.',
    overview:
      'Thousands of steps lead to Sri Pada. Most pilgrims climb overnight from Dalhousie for the summit dawn.',
    distanceKm: 7,
    durationHours: 5,
    difficulty: 'challenging',
    elevationGainM: 1000,
    scenicHighlights: ['Stairway of lights', 'Summit shrine', 'Shadow of the peak'],
    bestSeason: 'December–May pilgrimage season',
    safetyAdvice: ['Warm layers for summit', 'Steady pace', 'Descend carefully when tired'],
    nearbyAttractionHints: ['Hatton', 'Dalhousie village'],
    regionId: 'region-hill-country',
    images: [images.adventure.lantern, images.hero.main],
    featured: true,
  },
  {
    id: 'trail-diyaluma',
    name: 'Diyaluma Upper Pools',
    slug: 'diyaluma-upper-pools',
    shortDescription: 'Trail above one of Sri Lanka’s tallest waterfalls.',
    overview:
      'Hike to natural pools above Diyaluma Falls with wide dry-zone and highland transition views.',
    distanceKm: 4,
    durationHours: 3,
    difficulty: 'moderate',
    elevationGainM: 320,
    scenicHighlights: ['Upper pools', 'Falls overlook', 'Open ridges'],
    bestSeason: 'January–March',
    safetyAdvice: ['Slippery rock near water', 'Guide recommended for upper route'],
    nearbyAttractionHints: ['Wellawaya', 'Ella road lookouts'],
    regionId: 'region-uva-sabara',
    images: [images.destinations.waterfall, images.adventure.trail],
    featured: false,
  },
  {
    id: 'trail-knuckles',
    name: 'Knuckles Mini Traverse',
    slug: 'knuckles-mini-traverse',
    shortDescription: 'Cloud-forest ridges in the Knuckles range.',
    overview:
      'A sample of Knuckles biodiversity — mist forest, grasslands, and village edges northeast of Kandy.',
    distanceKm: 10,
    durationHours: 6,
    difficulty: 'challenging',
    elevationGainM: 700,
    scenicHighlights: ['Cloud forest', 'Ridgeline views', 'Village tea gardens'],
    bestSeason: 'January–March',
    safetyAdvice: ['Local guide strongly advised', 'Leeches after rain', 'Carry rain shell'],
    nearbyAttractionHints: ['Kandy', 'Matale'],
    regionId: 'region-hill-country',
    images: [images.experiences.natureWalk, images.map.territory],
    featured: false,
  },
  {
    id: 'trail-mihintale',
    name: 'Mihintale Sacred Ascent',
    slug: 'mihintale-ascent',
    shortDescription: 'Stair pilgrimage through ancient monastic terraces.',
    overview:
      'Climb stone stairs past stupas and caves where Buddhism’s Sri Lankan chapter traditionally began.',
    distanceKm: 2,
    durationHours: 2,
    difficulty: 'moderate',
    elevationGainM: 250,
    scenicHighlights: ['Mahaseya', 'Kantaka Chetiya', 'Tank-country views'],
    bestSeason: 'May–September mornings',
    safetyAdvice: ['Modest clothing', 'Hot stone at midday', 'Carry water'],
    nearbyAttractionHints: ['Anuradhapura', 'Kaludiya Pokuna'],
    regionId: 'region-cultural-triangle',
    images: [images.destinations.temple, images.destinations.sunrise],
    featured: false,
  },
];
