import { images } from '@/config/images';
import type { TravelRegion } from '@/types/travel';

export const mockRegions: TravelRegion[] = [
  {
    id: 'region-cultural-triangle',
    name: 'Cultural Triangle',
    slug: 'cultural-triangle',
    shortDescription: 'Ancient capitals, rock fortresses, and sacred cities of the dry zone.',
    overview:
      'The Cultural Triangle links Anuradhapura, Polonnaruwa, Sigiriya, and Dambulla — a landscape of stupas, reservoirs, and royal ruins that shaped Sri Lankan civilisation for over two millennia.',
    bestTimeToVisit: 'May–September (drier inland season); mornings for temple climbs.',
    highlights: ['Sigiriya Rock', 'Dambulla Cave Temple', 'Anuradhapura sacred city', 'Polonnaruwa ruins'],
    thingsToDo: ['Sunrise Pidurangala hike', 'Cycle ancient city roads', 'Visit living temples', 'Elephant corridor safaris near Habarana'],
    nature: 'Dry-zone scrub, ancient tanks, and seasonal elephant corridors around Minneriya and Kaudulla.',
    culture: 'Living Buddhism, pilgrimage routes, and crafts that still follow medieval patterns.',
    food: 'Rice and curry feasts, tank fish, and sweetmeats sold near temple towns.',
    photographySpots: ['Sigiriya summit light', 'Ruwanwelisaya at dusk', 'Gal Vihara rock Buddhas'],
    suggestedItineraries: [
      { title: 'Classic Triangle', days: '4 days', summary: 'Sigiriya–Dambulla–Polonnaruwa–Anuradhapura with one safari morning.' },
      { title: 'Slow Sacred Circuit', days: '6 days', summary: 'Add Mihintale, Aukana, and village stays between the capitals.' },
    ],
    nearbyCityIds: ['sigiriya', 'dambulla', 'anuradhapura', 'polonnaruwa', 'habarana'],
    attractionTags: ['historic', 'temple', 'nature'],
    images: [images.sriLanka.sigiriya, images.destinations.sunrise],
    featured: true,
  },
  {
    id: 'region-hill-country',
    name: 'Hill Country',
    slug: 'hill-country',
    shortDescription: 'Tea estates, cool air, and dramatic highland trails.',
    overview:
      'From Kandy’s lake and temples to Nuwara Eliya’s mist and Ella’s viewpoints, the central highlands are Sri Lanka’s green heart — train rides, waterfalls, and tea country walks.',
    bestTimeToVisit: 'January–March for clearer views; year-round for tea and temples.',
    highlights: ['Temple of the Tooth', 'Ella Rock & Nine Arch', 'Horton Plains', 'Tea estate tours'],
    thingsToDo: ['Scenic train to Ella', 'Little Adam’s Peak sunrise', 'World’s End hike', 'Kandy lake walk'],
    nature: 'Cloud forest, tea monocultures, highland lakes, and endemic birdlife.',
    culture: 'Kandyan dance, pilgrimage paths, and planter-era bungalows.',
    food: 'Fresh hill vegetables, milk toffee, and estate-fresh Ceylon tea.',
    photographySpots: ['Nine Arch Bridge', 'Lipton’s Seat', 'Lake Gregory reflections'],
    suggestedItineraries: [
      { title: 'Tea & Trails', days: '5 days', summary: 'Kandy–Nuwara Eliya–Ella with one full hiking day.' },
      { title: 'Highland Express', days: '3 days', summary: 'Train-focused run with Ella as base.' },
    ],
    nearbyCityIds: ['kandy', 'nuwara-eliya', 'ella', 'haputale', 'hatton', 'nugawela'],
    attractionTags: ['trail', 'tea_estate', 'waterfall', 'viewpoint', 'temple'],
    images: [images.sriLanka.tea, images.sriLanka.nineArch],
    featured: true,
  },
  {
    id: 'region-south-coast',
    name: 'South Coast',
    slug: 'south-coast',
    shortDescription: 'Forts, surf bays, whales, and palm-lined beaches.',
    overview:
      'Galle Fort anchors a coastline of Unawatuna, Hikkaduwa, Mirissa, and Tangalle — colonial ramparts, reef snorkelling, and seasonal blue whales offshore.',
    bestTimeToVisit: 'November–April for calm seas and whale watching.',
    highlights: ['Galle Fort', 'Mirissa whales', 'Hikkaduwa reef', 'Weligama surf'],
    thingsToDo: ['Walk fort ramparts', 'Sunrise Coconut Tree Hill', 'Learn to surf', 'Turtle conservation visits'],
    nature: 'Coral gardens, lagoons, stilt-fishing shores, and marine megafauna.',
    culture: 'Dutch fort living heritage, mask carving in Ambalangoda, fishing villages.',
    food: 'Fresh seafood curries, hoppers, and beachside grilled fish.',
    photographySpots: ['Galle Lighthouse', 'Jungle Beach cove', 'Parrot Rock'],
    suggestedItineraries: [
      { title: 'Fort to Bay', days: '4 days', summary: 'Galle base with day trips to Unawatuna and Mirissa.' },
      { title: 'Surf & Sea', days: '5 days', summary: 'Weligama/Mirissa focus with one whale morning.' },
    ],
    nearbyCityIds: ['galle', 'hikkaduwa', 'unawatuna', 'mirissa', 'weligama', 'tangalle'],
    attractionTags: ['historic', 'nature', 'adventure_stop', 'viewpoint'],
    images: [images.sriLanka.mirissa, images.sriLanka.galle],
    featured: true,
  },
  {
    id: 'region-east-coast',
    name: 'East Coast',
    slug: 'east-coast',
    shortDescription: 'Palm beaches, lagoons, and world-class point breaks.',
    overview:
      'Trincomalee, Passikudah, Batticaloa, and Arugam Bay offer a quieter coastal rhythm — Hindu cliff temples, calm bays, and monsoon-season surf.',
    bestTimeToVisit: 'May–September for east-coast surf and swimming.',
    highlights: ['Arugam Bay', 'Nilaveli & Pigeon Island', 'Koneswaram Temple', 'Passikudah bay'],
    thingsToDo: ['Surf Arugam Point', 'Snorkel Pigeon Island', 'Lagoon birding', 'Temple sunrise'],
    nature: 'Marine parks, lagoons, and dry-zone wildlife near the coast.',
    culture: 'Tamil and Muslim coastal towns, kovils, and fishing traditions.',
    food: 'Crab curries, string hoppers, and lagoon prawns.',
    photographySpots: ['Arugam Bay sunset', 'Nilaveli palms', 'Batticaloa lagoon bridges'],
    suggestedItineraries: [
      { title: 'East Escape', days: '5 days', summary: 'Trinco to Passikudah, then Arugam Bay.' },
    ],
    nearbyCityIds: ['trincomalee', 'nilaveli', 'passikudah', 'batticaloa', 'arugam-bay'],
    attractionTags: ['nature', 'adventure_stop', 'temple', 'viewpoint'],
    images: [images.sriLanka.unawatuna, images.sriLanka.mirissaCoast],
    featured: true,
  },
  {
    id: 'region-north',
    name: 'Northern Peninsula',
    slug: 'northern-peninsula',
    shortDescription: 'Jaffna’s temples, lagoons, and resilient culture.',
    overview:
      'Jaffna and the islands reveal a distinct northern identity — Nallur festival streets, Dutch fort walls, casuarina beaches, and lagoon cuisine.',
    bestTimeToVisit: 'May–September; festival season around Nallur (July/August).',
    highlights: ['Nallur Kandaswamy Temple', 'Jaffna Fort', 'Casuarina Beach', 'Point Pedro tip'],
    thingsToDo: ['Temple evening puja', 'Island day trips', 'Fort walk', 'Lagoon birding'],
    nature: 'Shallow lagoons, dunes, and migratory birds.',
    culture: 'Tamil Hindu traditions, rebuilt libraries, and war-to-peace storytelling.',
    food: 'Jaffna crab curry, odial kool, and palmyrah sweets.',
    photographySpots: ['Nallur gopuram', 'Fort ramparts', 'Point Pedro lighthouse'],
    suggestedItineraries: [
      { title: 'Jaffna Immersion', days: '4 days', summary: 'City temples, fort, and one island outing.' },
    ],
    nearbyCityIds: ['jaffna', 'nallur', 'point-pedro', 'chavakachcheri'],
    attractionTags: ['temple', 'historic', 'nature', 'market'],
    images: [images.destinations.temple, images.destinations.village],
    featured: true,
  },
  {
    id: 'region-wildlife',
    name: 'Wildlife Circuit',
    slug: 'wildlife-circuit',
    shortDescription: 'National parks, leopards, elephants, and bird wetlands.',
    overview:
      'Yala, Udawalawe, Wilpattu, Bundala, and Minneriya form Sri Lanka’s wildlife backbone — jeep safaris, wetland birding, and elephant gatherings.',
    bestTimeToVisit: 'Dry months vary by park; The Gathering at Minneriya peaks roughly July–September.',
    highlights: ['Yala leopards', 'Udawalawe elephants', 'Minneriya Gathering', 'Bundala birds'],
    thingsToDo: ['Dawn jeep safari', 'Elephant Transit Home', 'Wetland bird walk', 'Night sky in dry zone'],
    nature: 'Thorn scrub, grasslands, lagoons, and marine edges.',
    culture: 'Park-adjacent villages and pilgrimage towns like Kataragama.',
    food: 'Simple rice & curry, jungle-edge resthouses, fruit from roadside stalls.',
    photographySpots: ['Yala beach tracks', 'Udawalawe reservoir', 'Minneriya tank edge'],
    suggestedItineraries: [
      { title: 'South Wildlife', days: '4 days', summary: 'Yala + Udawalawe with Bundala birding.' },
      { title: 'Triangle Safari', days: '3 days', summary: 'Habarana base for Minneriya/Kaudulla.' },
    ],
    nearbyCityIds: ['yala-edge', 'tissamaharama', 'emibilipitiya', 'habarana', 'puttalam'],
    attractionTags: ['nature', 'adventure_stop'],
    images: [images.sriLanka.wildlife, images.sriLanka.galleAerial],
    featured: true,
  },
  {
    id: 'region-west-coast',
    name: 'West Coast & Colombo',
    slug: 'west-coast',
    shortDescription: 'Capital energy, lagoon wetlands, and resort beaches.',
    overview:
      'Colombo’s temples and markets meet Negombo’s lagoon, Bentota’s river mouth, and Kalutara’s coastal shrines — ideal arrivals and short coastal escapes.',
    bestTimeToVisit: 'December–March for calmer western seas.',
    highlights: ['Gangaramaya & Galle Face', 'Negombo lagoon', 'Bentota river', 'Kelaniya temple'],
    thingsToDo: ['City heritage walk', 'Lagoon boat safari', 'Beach sunset', 'Spice market browse'],
    nature: 'Urban wetlands like Muthurajawela, river estuaries, and beaches.',
    culture: 'Multi-faith capital, colonial streets, and coastal Catholic heritage.',
    food: 'Street kottu, Pettah snacks, and seafood along the coast.',
    photographySpots: ['Galle Face sunset', 'Lotus Tower skyline', 'Bentota estuary'],
    suggestedItineraries: [
      { title: 'Arrival Soft Landing', days: '2 days', summary: 'Colombo highlights plus Negombo lagoon.' },
    ],
    nearbyCityIds: ['colombo', 'negombo', 'bentota', 'kalutara', 'kelaniya'],
    attractionTags: ['temple', 'historic', 'market', 'nature', 'viewpoint'],
    images: [images.destinations.village, images.resort.dining],
    featured: false,
  },
  {
    id: 'region-uva-sabara',
    name: 'Uva & Sabaragamuwa',
    slug: 'uva-sabaragamuwa',
    shortDescription: 'Waterfalls, gem country, and rainforest edges.',
    overview:
      'Badulla, Wellawaya, Ratnapura, and Kitulgala combine tall falls, gem trading towns, and white-water rainforest — a bridge between highlands and dry plains.',
    bestTimeToVisit: 'January–March for clearer trails; rafting year-round with local advice.',
    highlights: ['Diyaluma Falls', 'Sinharaja gateway', 'Kitulgala rafting', 'Ratnapura gems'],
    thingsToDo: ['Upper Diyaluma pools', 'Gem museum visit', 'Rainforest birding', 'River adventure'],
    nature: 'Wet-zone rainforest, tall cascades, and highland-to-lowland transitions.',
    culture: 'Gem mining heritage and multi-faith Kataragama pilgrimages nearby.',
    food: 'River fish, jackfruit dishes, and estate snacks.',
    photographySpots: ['Diyaluma ledge', 'Nine Arch from Ella side', 'Kitulgala gorge'],
    suggestedItineraries: [
      { title: 'Falls & Forest', days: '4 days', summary: 'Ella/Wellawaya falls plus Kitulgala or Sinharaja edge.' },
    ],
    nearbyCityIds: ['ella', 'wellawaya', 'ratnapura', 'kitulgala', 'balangoda'],
    attractionTags: ['waterfall', 'trail', 'nature', 'market'],
    images: [images.destinations.waterfall, images.adventure.trail],
    featured: false,
  },
];
