import { images } from '@/config/images';
import type { TravelActivity } from '@/types/travel';

export const mockActivities: TravelActivity[] = [
  {
    id: 'act-ella-hike',
    name: 'Ella Highlands Hiking',
    slug: 'ella-highlands-hiking',
    shortDescription: 'Summit trails and tea-country ridges around Ella.',
    overview:
      'Combine Little Adam’s Peak, Ella Rock, and viewpoint walks for a full day of highland scenery — mist, tea, and valley light.',
    kind: 'hiking',
    difficulty: 'moderate',
    bestSeason: 'January–March for clearer views',
    duration: '4–8 hours',
    whatToBring: ['Trail shoes', 'Water', 'Rain layer', 'Sun protection'],
    safety: ['Start early for Rock trails', 'Stay on marked paths', 'Watch slick rock after rain'],
    nearbyRegionIds: ['region-hill-country'],
    images: [images.adventure.trail, images.hero.main],
    featured: true,
  },
  {
    id: 'act-yala-safari',
    name: 'Yala Wildlife Safari',
    slug: 'yala-wildlife-safari',
    shortDescription: 'Dawn jeep safari for leopards, elephants, and coastal scrub.',
    overview:
      'Explore Yala Block 1 with an experienced tracker. Early starts maximize wildlife sightings along beaches, lagoons, and thorn forest.',
    kind: 'wildlife',
    difficulty: 'easy',
    bestSeason: 'February–July (drier park tracks)',
    duration: 'Half day to full day',
    whatToBring: ['Neutral clothing', 'Binoculars', 'Camera', 'Dust scarf'],
    safety: ['Remain seated in vehicles', 'Follow ranger instructions', 'No feeding wildlife'],
    nearbyRegionIds: ['region-wildlife'],
    images: [images.experiences.natureWalk, images.map.territory],
    featured: true,
  },
  {
    id: 'act-whale-mirissa',
    name: 'Mirissa Whale Watching',
    slug: 'mirissa-whale-watching',
    shortDescription: 'Seasonal blue whale and dolphin boats from Mirissa harbour.',
    overview:
      'Morning departures head into deep water where blue whales migrate. Conditions and sightings vary — choose reputable operators.',
    kind: 'water',
    difficulty: 'easy',
    bestSeason: 'November–April',
    duration: '3–6 hours',
    whatToBring: ['Seasickness remedy', 'Light jacket', 'Sunglasses', 'Reusable bottle'],
    safety: ['Check swell forecasts', 'Wear life jackets as instructed', 'Respect wildlife distance rules'],
    nearbyRegionIds: ['region-south-coast'],
    images: [images.destinations.sunrise, images.resort.terrace],
    featured: true,
  },
  {
    id: 'act-surf-arugam',
    name: 'Arugam Bay Surfing',
    slug: 'arugam-bay-surfing',
    shortDescription: 'Point-break sessions and beginner bays on the east coast.',
    overview:
      'From the famous right-hand point to gentler beach breaks, Arugam Bay is Sri Lanka’s surf capital during the southwest monsoon.',
    kind: 'water',
    difficulty: 'moderate',
    bestSeason: 'May–September',
    duration: '2–4 hours per session',
    whatToBring: ['Reef-safe sunscreen', 'Rash guard', 'Water shoes optional'],
    safety: ['Know your level', 'Watch reef and currents', 'Surf with local advice'],
    nearbyRegionIds: ['region-east-coast'],
    images: [images.destinations.waterfall, images.adventure.trail],
    featured: true,
  },
  {
    id: 'act-tea-tour',
    name: 'Tea Plantation Experience',
    slug: 'tea-plantation-experience',
    shortDescription: 'Estate walks, factory tours, and fresh Ceylon tastings.',
    overview:
      'Walk contour paths between tea bushes, learn plucking and processing, and taste single-estate cups in the cool highlands.',
    kind: 'food',
    difficulty: 'easy',
    bestSeason: 'Year-round',
    duration: '2–3 hours',
    whatToBring: ['Comfortable shoes', 'Light sweater', 'Cash for estate shops'],
    safety: ['Stay on visitor paths', 'Mind factory machinery zones'],
    nearbyRegionIds: ['region-hill-country'],
    images: [images.experiences.teaTasting, images.hero.main],
    featured: true,
  },
  {
    id: 'act-kandy-culture',
    name: 'Kandy Cultural Immersion',
    slug: 'kandy-cultural-immersion',
    shortDescription: 'Temple rituals, lake walks, and Kandyan arts.',
    overview:
      'Experience the Temple of the Tooth precinct, lakeside promenades, and optional dance performances that keep highland traditions alive.',
    kind: 'culture',
    difficulty: 'easy',
    bestSeason: 'Year-round; Esala Perahera season is especially vivid',
    duration: 'Half day',
    whatToBring: ['Modest clothing for temples', 'Scarf for shoulders', 'Comfortable walking shoes'],
    safety: ['Follow temple etiquette', 'Secure belongings in crowds'],
    nearbyRegionIds: ['region-hill-country'],
    images: [images.destinations.temple, images.experiences.campfire],
    featured: true,
  },
  {
    id: 'act-train-ella',
    name: 'Scenic Train Journey',
    slug: 'scenic-train-journey',
    shortDescription: 'The legendary highland railway through tea country.',
    overview:
      'Ride the upcountry line between Kandy/Nanu Oya/Ella — open doors, viaducts, and endless green terraces.',
    kind: 'train',
    difficulty: 'easy',
    bestSeason: 'Clearer views January–March',
    duration: '2–7 hours depending on segment',
    whatToBring: ['Tickets in advance when possible', 'Snacks', 'Camera'],
    safety: ['Hold rails near open doors', 'Mind gaps at stations'],
    nearbyRegionIds: ['region-hill-country'],
    images: [images.adventure.trail, images.destinations.sunrise],
    featured: true,
  },
  {
    id: 'act-raft-kitulgala',
    name: 'Kitulgala White-Water Rafting',
    slug: 'kitulgala-rafting',
    shortDescription: 'Kelani River rapids through wet-zone rainforest.',
    overview:
      'Guided rafting runs through Kitulgala’s gorge — cinematic rainforest and refreshing river energy.',
    kind: 'adventure',
    difficulty: 'moderate',
    bestSeason: 'Year-round; water levels change with monsoon',
    duration: 'Half day',
    whatToBring: ['Swimwear', 'Secure footwear', 'Dry bag for phone'],
    safety: ['Listen to river guides', 'Wear provided helmet and PFD', 'Know swim ability'],
    nearbyRegionIds: ['region-uva-sabara'],
    images: [images.experiences.natureWalk, images.destinations.waterfall],
    featured: false,
  },
  {
    id: 'act-birding-bundala',
    name: 'Bundala Bird Watching',
    slug: 'bundala-bird-watching',
    shortDescription: 'Ramsar wetlands packed with migratory and resident birds.',
    overview:
      'Quiet jeep or walking birding in Bundala’s lagoons — flamingos in season, waders, and dry-zone specialties.',
    kind: 'wildlife',
    difficulty: 'easy',
    bestSeason: 'November–March for migrants',
    duration: '2–4 hours',
    whatToBring: ['Binoculars', 'Hat', 'Muted clothing'],
    safety: ['Stay with guide', 'Respect nesting distances'],
    nearbyRegionIds: ['region-wildlife'],
    images: [images.destinations.waterfall, images.experiences.natureWalk],
    featured: false,
  },
  {
    id: 'act-snorkel-pigeon',
    name: 'Pigeon Island Snorkelling',
    slug: 'pigeon-island-snorkelling',
    shortDescription: 'Coral gardens off Nilaveli on the east coast.',
    overview:
      'Boat to Pigeon Island National Park for shallow reefs and bright fish — best in the east-coast season.',
    kind: 'water',
    difficulty: 'easy',
    bestSeason: 'May–September',
    duration: 'Half day',
    whatToBring: ['Reef-safe sunscreen', 'Swimwear', 'Waterproof camera'],
    safety: ['Do not stand on coral', 'Check park ticket rules', 'Watch boat ladders'],
    nearbyRegionIds: ['region-east-coast'],
    images: [images.resort.terrace, images.destinations.sunrise],
    featured: false,
  },
  {
    id: 'act-village-food',
    name: 'Village Food Experience',
    slug: 'village-food-experience',
    shortDescription: 'Home-style cooking, markets, and spice garden tastes.',
    overview:
      'Join a village kitchen or market walk to learn hoppers, sambols, and spice blends with local hosts.',
    kind: 'food',
    difficulty: 'easy',
    bestSeason: 'Year-round',
    duration: '3–4 hours',
    whatToBring: ['Appetite', 'Modest clothing', 'Cash for market buys'],
    safety: ['Ask about spice levels', 'Drink bottled or boiled water if unsure'],
    nearbyRegionIds: ['region-hill-country', 'region-west-coast'],
    images: [images.experiences.teaTasting, images.destinations.village],
    featured: false,
  },
  {
    id: 'act-photo-tour',
    name: 'Landscape Photography Tour',
    slug: 'landscape-photography-tour',
    shortDescription: 'Guided golden-hour shoots at iconic viewpoints.',
    overview:
      'Target sunrise and sunset locations — Nine Arch, Sigiriya views, or coastal forts — with composition tips for travelers.',
    kind: 'adventure',
    difficulty: 'easy',
    bestSeason: 'Depends on region; clear dry-season mornings preferred',
    duration: 'Half day',
    whatToBring: ['Camera or phone', 'Tripod optional', 'Headlamp for dawn starts'],
    safety: ['Watch cliff edges', 'Respect private property and temples'],
    nearbyRegionIds: ['region-hill-country', 'region-cultural-triangle', 'region-south-coast'],
    images: [images.destinations.sunrise, images.adventure.trail],
    featured: false,
  },
];
